name: Deploy HTML Files to AppServices - CMST385

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AppServicesCMST385 }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cmst385-umgc-kstarken1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AppServicesCMST385 }}
